services:
    db:
        image: mysql:latest
        container_name: le_recyclotron_db
        ports:
            - "3306:3306"
        env_file:
            - .env
        volumes:
            - ./db-script/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
        restart: unless-stopped
        networks:
            - recyclotron_network

    backend:
        container_name: le_recyclotron_backend
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - "3000:3000" # Ensure this is correct
        env_file:
            - .env
        restart: unless-stopped
        networks:
            - recyclotron_network

networks:
    recyclotron_network:
        name: recyclotron_network
        driver: bridge
