graph TB
    style CategoryRoutes fill:#672d2d
    style A fill:#FF6B6B
    style B fill:#FF6B6B
    style C fill:#FF6B6B
    style D fill:#FF6B6B
    style E fill:#FF6B6B
    style F fill:#FF6B6B
    style G fill:#FF6B6B
    style H fill:#FF6B6B
    style I fill:#FF6B6B
    style J fill:#FF6B6B
    style K fill:#FF6B6B
    style L fill:#FF6B6B
    style M1 fill:#FF6B6B
    style N1 fill:#FF6B6B

    subgraph CategoryRoutes
        subgraph POST /categories
            direction LR
            A[InputCategory :
            - name : string] -->|createCategory| B[Category :
            - id : number 
            - name : string]
        end
        subgraph POST/categories/:id/categories
            direction LR
            M1[ id : string,
            InputCategory :
            - name : string] -->|createChildCategory| N1[Category :
            - id : number 
            - name : string
            - parent_category_id: number]
        end
        subgraph GET /categories
            direction LR
            C[None] -->|getAllCategories| D[Array of Category :
            - id : number 
            - name : string
            - parent_category_id?: number]
        end
        subgraph GET /categories/:id
            direction LR
            E[id: string] -->|getCategoryById| F[Category :
            - id : number 
            - name : string
            - parent_category_id?: number]
        end
        subgraph PUT /categories/:id
            direction LR
            G[id: string, 
            PartialCategory :
            - name?: string
            - parent_category_id?: number] -->|updateCategoryById| H[Category :
            - id : number 
            - name : string
            - parent_category_id?: number]
        end
        subgraph DELETE /categories/:id
            direction LR
            I[id: string] -->|deleteCategoryById| J[None]
        end
        subgraph GET/categories/:id/categories
            direction LR
            K[id: string] -->|getAllCategoriesOfCategory| L[Array of Category :
            - id : number 
            - name : string
            - parent_category_id: number]
        end
    end

    style EventRoutes fill:#5c4188
    style M fill:#845EC2
    style N fill:#845EC2
    style O fill:#845EC2
    style P fill:#845EC2
    style Q fill:#845EC2
    style R fill:#845EC2
    style S fill:#845EC2
    style T fill:#845EC2
    style U fill:#845EC2
    style V fill:#845EC2
    style W fill:#845EC2
    style X fill:#FF7F3F

    subgraph EventRoutes
        subgraph POST /event
            direction LR
            M[InputEvent :
            - title: string
            - image: string
            - desc: string
            - date: date] -->|createEvent| N[Event :
            - id: number
            - title: string
            - image: string
            - desc: string
            - date: date]
        end
        subgraph GET /event
            direction LR
            O[None] -->|getAllEvents| P[Array of Event :
            - id: number
            - title: string
            - image: string
            - desc: string
            - date: date]
        end
        subgraph GET /event/:id
            direction LR
            Q[id: string] -->|getEventById| R[Event :
            - id: number
            - title: string
            - image: string
            - desc: string
            - date: date]
        end
        subgraph PUT /event/:id
            direction LR
            S[id: string, 
            PartialEvent :
            - id: number
            - title: string
            - image: string
            - desc: string
            - date: date] -->|updateEvent| T[Event :
            - id: number
            - title: string
            - image: string
            - desc: string
            - date: date]
        end
        subgraph DELETE /event/:id
            direction LR
            U[id: string] -->|deleteEvent| V[None]
        end
        subgraph GET/event/:id/registration
            direction LR
            W[id: string] -->|getEventRegistrations| X[Array of Registration :
            - id: number
            - date: date
            - seats: number]
        end
    end
    
    style ItemsRoutes fill:#1d685f
    style Y fill:#2A9D8F
    style Z fill:#2A9D8F
    style AA fill:#2A9D8F
    style AB fill:#2A9D8F
    style AC fill:#2A9D8F
    style AD fill:#2A9D8F
    style AE fill:#2A9D8F
    style AF fill:#2A9D8F
    style AG fill:#2A9D8F
    style AH fill:#2A9D8F
    style AI fill:#2A9D8F
    style AJ fill:#2A9D8F
    style AK fill:#2A9D8F
    style AL fill:#02b7c9
    style AM fill:#2A9D8F
    style AN fill:#FF6B6B
    style AO fill:#2A9D8F
    style AP fill:#2A9D8F

    subgraph ItemsRoutes
        subgraph POST /items
            direction LR
            Y[InputItem :
            - name: string
            - status: ItemStatus
            - material: string
            - image: string
            - date: Date] -->|createItem| Z[Item :
            - id: number
            - name: string
            - status: ItemStatus
            - material: string
            - image: string
            - date: Date]
        end
        subgraph GET /items
            direction LR
            AA[None] -->|getAllItems| AB[Array of Item :
            - id: number
            - name: string
            - status: ItemStatus
            - material: string
            - image: string
            - date: Date]
        end
        subgraph GET /items/:id
            direction LR
            AC[id: string] -->|getItemById| AD[Item :
            - id: number
            - name: string
            - status: ItemStatus
            - material: string
            - image: string
            - date: Date]
        end
        subgraph GET /items/:status
            direction LR
            AE[status: string] -->|getItemsByStatus| AF[Item :
            - id: number
            - name: string
            - status: ItemStatus
            - material: string
            - image: string
            - date: Date]
        end
        subgraph PUT /items/:id
            direction LR
            AG[id: string, 
            PartialItem :
            - id: number
            - name: string
            - status: ItemStatus
            - material: string
            - image: string
            - date: Date] -->|updateItemById| AH[Item :
            - id: number
            - name: string
            - status: ItemStatus
            - material: string
            - image: string
            - date: Date]
        end
        subgraph DELETE /items/:id
            direction LR
            AI[id: string] -->|deleteItemById| AJ[None]
        end
        subgraph POST /items/:id/categories
            direction LR
            AK[itemId: string, categoryId: string] -->|addCategoryToItem| AL[ItemCategory :
            - itemId : number
            - categoryId : number]
        end
        subgraph GET /items/:id/categories
            direction LR
            AM[id: string] -->|getAllCategoriesOfItem| AN[Array of Category :
            - id : number 
            - name : string
            - parent_category_id?: number]
        end
        subgraph DELETE/items/:id/categories/:id
            direction LR
            AO[itemId: string, 
            categoryId: string] -->|deleteCategoryOfItem| AP[None]
        end
    end

    style PaymentRoutes fill:#43567e
    style AQ fill:#5c77b0
    style AR fill:#5c77b0
    style AS fill:#5c77b0
    style AT fill:#5c77b0
    style AU fill:#5c77b0
    style AV fill:#5c77b0
    style AW fill:#5c77b0
    style AX fill:#5c77b0
    style AY fill:#5c77b0
    style AZ fill:#5c77b0

    subgraph PaymentRoutes
        subgraph POST /subscription
            direction LR
            AQ[SubscriptionBody :
            - customerId: string
            - priceId: string
            - userId: number] -->|createSubscription| AR[subscriptionId : string]
        end
        subgraph DELETE /subscription/:id
            direction LR
            AS[subscriptionId: string] -->|cancelSubscription| AT[None]
        end
        subgraph POST /donation
            direction LR
            AU[DonationBody :
            - amount: number,
            - paymentMethodId: string,
            - userId: number,
            ] -->|createDonation| AV[clientSecret: string]
        end
        subgraph PUT /payment-method
            direction LR
            AW[PaymentMethodBody :
            - customerId: string
            - paymentMethodId: string] -->|updatePaymentMethod| AX[success : boolean]
        end
        subgraph POST /webhook
            direction LR
            AY[None] -->|handleWebhook| AZ[received : boolean]
        end
    end

    style RegistrationRoutes fill:#a1552f
    style BA fill:#FF7F3F
    style BB fill:#FF7F3F
    style BC fill:#FF7F3F
    style BD fill:#FF7F3F
    style BE fill:#FF7F3F
    style BF fill:#FF7F3F
    style BG fill:#FF7F3F
    style BH fill:#FF7F3F
    style BI fill:#FF7F3F
    style BJ fill:#FF7F3F

    subgraph RegistrationRoutes
        subgraph POST /registration
            direction LR
            BA[InputRegistration :
            - userId: number
            - eventId: number
            - seats : number] -->|createRegistration| BB[Registration :
            - id : number
            - userId: number
            - eventId: number
            - date : date
            - seats : number]
        end
        subgraph GET /registration
            direction LR
            BC[None] -->|getAllRegistrations| BD[Array of Registration :
            - id : number
            - userId: number
            - eventId: number
            - date : date
            - seats : number]
        end
        subgraph GET /registration/:id
            direction LR
            BE[id: string] -->|getRegistration| BF[Registration :
            - id : number
            - userId: number
            - eventId: number
            - date : date
            - seats : number]
        end
        subgraph PUT /registration/:id
            direction LR
            BG[id: string, 
            PartialRegistration :
            - userId: number
            - eventId: number
            - seats : number] -->|updateRegistration| BH[Registration :
            - id : number
            - userId: number
            - eventId: number
            - date : date
            - seats : number]
        end
        subgraph DELETE /registration/:id
            direction LR
            BI[id: string] -->|deleteRegistration| BJ[None]
        end
    end

    style UserRoutes fill:#9f799f
    style BK fill:#ae00ae
    style BL fill:#ae00ae
    style BM fill:#ae00ae
    style BN fill:#ae00ae
    style BO fill:#ae00ae
    style BP fill:#ae00ae
    style BQ fill:#ae00ae
    style BR fill:#ae00ae
    style BS fill:#ae00ae
    style BT fill:#ae00ae
    style BU fill:#ae00ae
    style BV fill:#ae00ae
    style BW fill:#ae00ae
    style BX fill:#ae00ae
    style BW1 fill:#ae00ae
    style BX1 fill:#5c77b0
    style BW2 fill:#ae00ae
    style BX2 fill:#FF7F3F
    style BW3 fill:#ae00ae
    style BX3 fill:#ae00ae
    style BW4 fill:#ae00ae
    style BX4 fill:#ae00ae
    subgraph UserRoutes
        subgraph POST /users
            direction LR
            BK[CreateUser :
            - first_name: string
            - last_name: string
            - email: string
            - password: string
            - is_adherent: boolean
            - phone?: string
            - sub_type?: string] -->|createUser| BL[User :
            - id: number
            - first_name: string
            - last_name: string
            - email: string
            - phone?: string
            - is_adherent: boolean
            - sub_type?: string
            - roles : Array of Object : id : number, name : string]
        end
        subgraph GET /users
            direction LR
            BM[None] -->|getAllUsers| BN[Array of User :
            - id: number
            - first_name: string
            - last_name: string
            - email: string
            - phone?: string
            - is_adherent: boolean
            - sub_type?: string
            - roles : Array of Object : id : number, name : string]
        end
        subgraph GET /users/:id
            direction LR
            BO[id: string] -->|getUserById| BP[User :
            - id: number
            - first_name: string
            - last_name: string
            - email: string
            - phone?: string
            - is_adherent: boolean
            - sub_type?: string
            - roles : Array of Object : id : number, name : string]
        end
        subgraph PUT /users/:id
            direction LR
            BQ[id: string, UpdateUser :
            - first_name?: string
            - last_name?: string
            - email?: string
            - phone?: string
            - password?: string
            - is_adherent?: boolean
            - sub_type?: string] -->|updateUser| BR[User :
            - id: number
            - first_name: string
            - last_name: string
            - email: string
            - phone?: string
            - is_adherent: boolean
            - sub_type?: string
            - roles : Array of Object : id : number, name : string]
        end
        subgraph DELETE /users/:id
            direction LR
            BS[id: string] -->|deleteUser| BT[None]
        end
        subgraph POST /users/:id/roles
            direction LR
            BU[id: string, roles: Array of number] -->|addUserRoles| BV[User :
            - id: number
            - first_name: string
            - last_name: string
            - email: string
            - phone: string
            - password: string
            - is_adherent: boolean
            - sub_type: string
            - roles : Array of Object : id : number, name : string]
        end
        subgraph DELETE/users/:userId/roles/:roleId
            direction LR
            BW[userId: string, 
            roleId: string] -->|removeUserRoles| BX[User :
            - id: number
            - first_name: string
            - last_name: string
            - email: string
            - phone: string
            - password: string
            - is_adherent: boolean
            - sub_type: string
            - roles : Array of Object : id : number, name : string]
        end
        subgraph GET /users/:id/payments
            direction LR
            BW1[id: string] -->|getPaymentsByUserId| BX1[Array of Payment :
            - id : number
            - userId: number
            - id_stripe_payment: string
            - amount: float
            - type: number
            - status: string]
        end
        subgraph GET/users/:id/registrations
            direction LR
            BW2[id: string] -->|getRegistrationsByUserId| BX2[Array of Registration :
            - id : number
            - userId: number
            - eventId: number
            - date : date
            - seats : number]
        end
        subgraph POST /users/forgot-password
            direction LR
            BW3[ResetPasswordRequest
            ] -->|forgotPassword| BX3[None]
        end
        subgraph POST /users/reset-password
            direction LR
            BW4[ResetPassword
            ] -->|resetPassword| BX4[None]
        end
    end

    style AuthRoutes fill:#4a6741
    style BY fill:#6B8E23
    style BZ fill:#6B8E23
    style CA fill:#6B8E23
    style CB fill:#6B8E23
    style CE fill:#6B8E23
    style CF fill:#6B8E23
    style CG fill:#6B8E23
    style CH fill:#ae00ae
    style CI fill:#6B8E23
    style CJ fill:#6B8E23
    style CK fill:#6B8E23
    style CL fill:#6B8E23
    
    subgraph AuthRoutes
        subgraph POST /auth/login
            direction LR
            BY[email: string,
            password: string] -->|login| BZ[None]
        end
        subgraph POST /auth/register
            direction LR
            CA[CreateUser :
            - email: string
            - password: string
            - first_name: string
            - last_name: string
            - phone?: string] -->|register| CB[None]
        end
        subgraph POST /auth/verify_otp
            direction LR
            CE[id: string,
            otp: string] -->|verifyOTP| CF[JWT]
        end
        subgraph GET /auth/me
            direction LR
            CG[None] -->|getCurrentUser| CH[User : 
            - id: number
            - first_name: string
            - last_name: string
            - email: string
            - phone?: string
            - is_adherent: boolean
            - sub_type?: string]
        end
        subgraph POST /auth/revoke-all
            direction LR
            CI[None] -->|revokeAllTokens| CJ[None]
        end
        subgraph POST /auth/revoke-user/:id
            direction LR
            CK[id: string] -->|revokeUserTokens| CL[None]
        end
    end